



route = [["jayanagar 4th block", "south end", "gandhi bazaar", "goods shed road", "majestic", "malleshwaram", "yeshvantapur railway station"],
["ssmrv", "jayanagar", "lalbagh", "town hall", "j.p.nagar 6th phase"],
["ssmrv", "jayanagar", "lalbagh", "town hall", "indira gandhi circle"],
["jp nagar 15th cross", "ssmrv", "tel exchange", "eliyas eagar"],
["lalbagh", "corporation", "majestic", "sujatha talkies", "eliyas nagar"],
["ramakrishna ashram", "gandhi bazaar", "jayanagar 9th block"],
["gandhi bazaar", "jayanagar 4th block", "east end", "btm layout"],
["gandhi bazaar", "jayanagar 4th block"],
["mysore road satellite bus stop", "hoskerehalli cross", "kamakya", "jp nagar 6th phase", "j p nagar 3rd phase"],
["lalbagh", "nanda theatre", "sangam circle", "banashankari"],
["lalbagh", "yediyur", "monotype", "yarabnagar"],
["lalbagh", "yediyur", "banashankari bda complex", "padmanabhanagar"],
["lalbagh", "yediyur", "jayanagar 7th block", "banashankari bus stand"],
["jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand,richmond circle", "dayanandsagar college", "shivajinagar"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand", "richmond circle", "shivajinagar"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
["shanthi talkies", "gandhi bazaar", "chamrajpet", "kr market", "corporation", "swastik", "malleshwaram bus station"],
["basavanagudi", "kumaraswamy layout", "padmanabhanagar"],
["kr market", "basavanagudi", "kumaraswamy layout"],
["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "18th main", "jayanager 9th block"],
["indian express", "richmond circle", "k h road", "lalbagh", "south end circle", "jayanagar 3rd block", "jayanagar 4th block", "jayanagar 9th block"],
["jayanagar 4th block", "madhavan park", "ashoka pillar", "lalbagh west gate", "kims hospital/makkalakoota"],
["jayanagar 4th block", "madhavan park", "ashoka pillar", "lalbagh west gate", "j c road", "corporation"],
["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "sanjay gandhi hospital", "jayanager east end (jayadeva hospital)", "udupi garden", "btm layout (kuvempunagar)"],
["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "sanjay gandhi hospital", "jayanager east end (jayadeva hospital", "j.p.nagar 3rd phase"],
["ashoka piller", "siddapura"],
["jayanagar 4th block", "ashoka pillar", "gandhibazaar", "k r market", "vidhana soudha", "shivananda", "vyalikaval"],
["gandhi bazaar", "chamrajpet", "kr market", "corporation", "kaveri bhavan", "vasanth nagar", "jc nagar", "rehmath nagar"],
["chamrajpet", "kr market", "town hall", "mysore bank circle", "shivananda circle", "malleshwaram circle"],
["srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["vivekanandanagar", "srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["srinivasanagar", "ramkrishna ashram", "lalbagh west gate", "shantinagar"],
["double road", "richmond circle", "brigade road", "mg road", "trinity circle", "cmh road", "indiranagar"],
["malleswaram 8th cross", "swastik", "corporation", "lalbagh main gate"],
["srinivasnagar", "ganesh bhavan", "ramkrishna ashram", "uma talkies", "kr market", "corporation"],
["srinivasnagar", "ganesh bhavan", "ramkrishna ashram", "uma talkies", "kr market", "corporation"],
["banashankari 1st stage", "hanmanthnagara ward office", "chamrajpet", "kr market", "cantonment railway station", "jc nagar", "rehmat nagar"],
["banashankari 1st stage", "chamarajapete", "k r market"],
["banashankari 1st stage", "chamarajapete", "k r market"],
["banashankari 1st stage", "chamarajapete", "k r market", "corporation"],
["banashankari 1st stage", "chamarajapete", "k r market"],
["watertank", "banashankari 1st stage", "chamarajapete", "k r market", "corporation"],
["janta bazaar", "banashankari 1st stage", "chamarajapete", "k r market", "corporation"],
["banashankari 1st stage", "chamarajapete", "k r market", "corporation"],
["mysore road"],
["maruti mandir (vijayanagar)", "garage (vijayanagar)", "attiguppe (vijayanagar)", "deepanjali nagar", "bapujinagar", "chamarajpet", "ram mmandir (chamarajpet)", "makkalakoota", "kr market."],
["jayanagar 9th block", "jayanagar south end", "gandhi bazaar", "mysore road satellite bus stand"],
["vijaynagar"],
["vijaynagar", "rajajinagar 6th block", "sujatha"],
["vijaynagar (maruthi mandir)", "vijaynagar", "rajajinagar 6th block", "sujatha"],
["vijaynagar"],
["vijaynagar", "west of chord road", "yeshwantpur"],
["via south end", "gandhi bazaar", "chamrajpet", "magadi road"],
["rajajinagar"],
["malleshwaram", "srirampura", "rajajinagar"],
["chamrajpet", "magadi road"],
["saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mandir", "sujatha talkies", "okalipura"],
["nandini layout", "saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mandir", "sujatha talkies", "okalipura"],
["nandini layout", "saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mandir", "sujatha talkies", "okalipura"],
["jayanagar 4th block", "kempegowda bus station", "magadi road"],
["okallipuram", "magadi road", "prasanna", "tollgate", "pipe line", "railway gate"],
["sujatha", "ram mandir"],
["sujatha"],
["central", "malleshwaram", "rajajinagar", "modi hospital", "basaweshwaranagar", "sujatha"],
["malleshwaram 8th main"],
["sujatha", "basaveshwaranagar", "modi hospital", "rajajinagar", "malleshwaram", "central"],
["sujatha", "basaveshwaranagar"],
["sujatha,ram mandir", "basaveshwarnagar"],
["central", "devaiah park", "modi hospital"],
["modi hospital(basaveshwarnagar)"],
["mount carmel", "shivajinagar", "shantinagar", "adugodi", "koramangla"],
["sadashivanagar", "guttahalli main road", "link road", "central"],
["shivajinagar", "jayanagar 4th block"],
["indian express", "richmond cirlce", "koramangala"],
["cbi", "shankar mutt"],
["indian express", "corporation", "kr market"],
["rt nagar", "matadahalli", "kg road"],
["kg road"],
["cqal", "borebank road"],
["100ft road indiranagar", "ulsoor"],
["malleshwaram", "mount carmel", "indian express", "ulsoor", "indiranagar"],
["malleshwaram", "mount carmel", "indian express", "ulsoor", "indiranagar"],
["corporation", "residency road", "mg road", "ulsoor", "indiranagar", "thippasandra cross"],
["vidhana soudha", "shivajinagar", "ulsoor", "indiranagar", "thippasandra cross"],
["ulsoor", "indiranagar", "thippasandra cross"],
["shivajinagar"],
["yeshvantapur", "mekhri circle", "shivajinagar"],
["shivajinagar"],
["jayanagar 4th block", "btm layout", "silk board"],
["kempegowda bus station", "shantinagar"],
["wilson garden", "majestic"],
["mekhri circle", "vyalikaval", "malleshwaram circle", "navarang", "vijayanagar", "maruthi mandir"],
["mekhri circle", "yeshvantapur"],
["magadi road", "kr market", "lalbagh west gate", "jayanagar 4th block"],
["vyalikaval", "malleshwaram circle"],
["hanumanthanagar", "town hall", "malleshwaram"],
["hanumanthanagar", "jc road", "town hall", "majestic", "malleshwaram"],
["via majestic", "malleshwaram circle"],
["via hanumanthanagar", "ramakrishna ashram", "lalbagh", "richmond circle", "ulsoor", "indiranagar"],
["via indiranagar", "ulsoor", "shivajinagar", "cantonment railway station", "jc nagar", "rt nagar"],
["indiranagar", "ulsoor", "austin town", "vivek nagar", "kormangala 100ft road", "madivala", "silk board", "banashankari", "katriguppe", "hosakerehalli cross", "srinivasanagar"],
["indiranagar 100ft road", "domlur layout", "inner ring road", "kormangala"],
["thippasandra cross", "cmh road", "indiranagar 100ft road", "domlur layout", "inner ring road", "kormangala", "madivala", "silk board", "btm layout", "jayanagar 5th block"],
["thippasandra cross", "cmh road", "indiranagar 100ft road", "inner ring road", "kormangala", "madivala", "silk board", "banashankari", "devegowda petrol bunk"],
["madivala", "silk board", "btm layout", "jayanagar 5th block", "banashankari", "devegowda petrol bunk"],
["thippasandra cross", "cmh road", "indiranagar 100ft road", "inner ring road", "kormangala", "madivala", "silk board", "banashankari", "devegowda petrol bunk", "pesit", "nayandahalli cross", "attiguppe"],
["thippasandra cross", "cmh road", "indiranagar 100ft road", "domlur layout", "inner ring road", "kormangala"],
["btm", "silk board", "dell"],
["btm", "silk board", "indiranagar"],
["beml gate", "thippasandra cross", "cmh road", "indiranagar 100ft road", "kormangala", "madivala", "silk board", "banashankari", "katriguppe", "hosakerehalli cross", "bank colony", "hanumanthnagar"],
["beml gate", "thippasandra cross", "cmh road", "indiranagar 100 feet road", "inner ring road", "kormangala", "madivala", "silk board", "btm layout", "jayanagar 5th block", "banashankari", "kadirenahalli cross"],
["indiranagar 100ft road", "cmh road", "trinity circle", "adugodi", "madiwala", "silkboard", "btm layout", "jayanagar 5th block"],
["devegowda petrol bunk", "banashankari", "btm layout", "silk board", "madivala", "koramangala", "inner ring road", "indiranagar 100ft road"],
["east end", "btm", "silk board", "koramangla water tank", "koramangla sony world"],
["kr market", "basavanagudi,dayanandsagar college,kumarswamy layout"],
["banashankari", "jayanagar 4th block", "shantinagar bus stand,dayanandsagar college,kumarswamy layout"],
["kr market", "basavanagudi,dayanandsagar college"],
["kr market", "basavanagudi,dayanandsagar college,kumarswamy layout"],
["banashankari", "konanakunte cross", "kaggalipura"],
["banashankari", "konanakunte cross", "art of living", "udayapura", "sln stores(appaji stores)"],
["banashankari", "konanakunte cross", "kaggalipura", "kebbagodi cross"],
["banashankari", "konanakunte cross", "gottigere"],
["mctc", "nayandanahalli", "kengeri"],
["via basavanagudi", "banashankari", "uttarahalli"],
["nayandahalli", "banashankari"],
["via banashankari", "uttarahalli"],
["via ideal homes rajarajeshwarinagar gate", "rajarajeswari temple"],
["banashankari", "btm", "silk board"],
["via viajayanagar", "mctc", "chamrajpet"],
["kamakshipalya", "khb colony", "vijayanagar", "mctc", "chamrajpet"],
["hegganahalli", "sunkadakatte", "kamakshipalya", "khb colony", "vijayanagar", "mctc"],
["via sunkadgatte,240p"],
["mathikere", "mekhri circle", "shivajinagar", "shantinagar", "jayanagar 4th block"],
["via jayanagar ttmc", "lalbagh", "corporation", "swastik", "malleshwaram 18th cross"],
["kempegowda bus station", "corporation", "shantinagar", "madiwala", "bommanahalli"],
["bel circle", "mathikere", "kempegowda bus station", "kr market", "basavanagudi"],
["mekhri circle", "shivajinagar", "ulsoor"],
["corporation", "kr market,276n"],
["majestic", "shivananda", "mekhri circle", "hebbala", "kodighalli", "yelahanka police station", "hunsamanhalli", "kodagulati", "hosahalli."],
["majestic", "shivananda", "mekhri circle", "hebbala", "kodighalli", "yelahanka police station", "hunsamanhalli", "kodagulati."],
["majestic", "shivananda", "mekhri circle", "hebbala", "kodighalli", "yelahanka nes", "ananthapura gate."],
["majestic", "shivananda", "mekhri circle", "hebbala", "kodighalli", "yelahanka nes", "ananthapura gate", "rajankunte."],
["mekhri circle", "hebbala", "kodighalli", "yelahanka nes", "ananthapura gate,rajankunte."],
["mekhri circle", "hebbala", "kodighalli."],
["mekhri circle", "hebbala", "sahakar nagar."],
["shivananda", "mekhri circle", "hebbala", "kodighalli", "yelahanka police station", "yelahanka old town."],
["frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "shivajinagar."],
["iti circle", "ramamurthy nagar", "ring road", "banaswadi", "uttam sagar", "ayyappa temple", "indian oil", "maruthi sevanagar", "jai bharath nagar", "itc", "mosque road", " frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "shivajinagar."],
["babusapalya", "mantap", "om shakti temple", "uttam sagar", "ayyappa temple", "indian oil", "maruthi sevanagar", "jai bharath nagar", "itc", "mosque road", "frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "vidhan soudha", "kr circle", "mysore bank", "kbs."],
["shivajinagar", "shantinagar", "jayanagar 4th block"],
["banaswadi", "shivajinagar", "shantinagar"],
["mg road", "ulsoor", "indiranagar", "thippasandra", "beml gate"],
["mg road", "ulsoor", "indiranagar", "thippasandra", "beml gate", "cv raman nagar", "kaggadasapura"],
["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate"],
["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "mallesh palya"],
["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "cv raman nagar", "kaggadasapura"],
["town hall", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "vignana nagar"],
["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "gm palya"],
["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "g m palya"],
["thippasandra", "cmh road", "trinity circle", "vellara junction", "kh road", "lalbagh west gate", "national college", "hanumantanagar"],
["mg road", "ulsoor", "indiranagar", "thippasandra", "malleshpalya"],
["kasturinagar", "channasandra railway bridge", "ramamurthy nagar"],
["corporation", "bishop cottons", "m g road", "ulsoor", "indiranagar depot", "byapanahalli", "tin factory", "k r puram", "hoskote"],
["isolation hospital", "kasturinagar"],
["kadugodi", "varthur", "bommasandra"],
["kadugodi", "whitefield", "varthur", "bommsandra", "sarjapura", "indiabele"],
["town hall", "corporation", "mg road", "domlur", "hal", "marathalli", "siddapura", "kodi", "varthur", "madhura nagar", "vaalepura"],
["mg road", "domlur", "hal", "marathalli", "siddapura", "kodi", "varthur", "madhura nagar", "vaalepura"],
["hal", "marathahalli", "vathoor kodi", "whitefield", "kadugodi", "(kbs to itpl)", "domlur", "hal", "marathahalli", "kundalahalli gate"],
["chandapura", "electronic city", "madiwala", "silk board"],
["mekhri circle", "kempegowda bus station", "madiwala"],
["kempegowda bus station", "dairy circle"],
["jalahalli cross", "kr market", "lalbagh", "jayanagar 4th block"],
["jayanagar east end", "jayanagar 4th block", "gandhi bazaar", "mctc"],
["via kengeri", "uttarahalli,jayanagar ttmc"],
["kengeri", "uttarahalli", "banashankari", "silk board", "bommanhalli"],
["jayanagar", "banashankari", "uttarahalli", "kengeri"],
["via uttarahalli", "konanakunte cross", "gottigere", "bettadasapura", "neeladri", "wipro"],
["jayanagar 5th block", "jp nagar 1st phase", "jambusavari dinne", "gottigere", "378 route"],
["attibelle", "sarjapura", "dommsandra", "varthur", "kadugodi"],
["attibelle", "sarjapur"],
["vidyaranyapura", "mathikere", "hosakerehalli cross"],
["vidyaranyapura", "mathikere", "yeshvantapur", "isckon", "west of chord road", "vijayanagar"],
["gorguntepalya", "kamakshipalya", "nagarbhavi bda complex", "kengeri satellite town"],
["kengeri satellite town", "west of chord road", "yeshwanthpur"],
["west of chord road"],
["rajajinagar", "vijayanagar", "nayandahalli", "kamakya"],
["majestic", "mekhri circle", "hebbal", "yelahanka nes", "upanagara."],
["mekhri circle", "hebbal", "yelahanka nes", "upanagara."],
["mekhri circle", "hebbal", "yelahanka nes", "upanagara."],
["kr road", "kr market", "kempegowda bus station", "hebbal"],
["banashankari", "kr road", "kr market", "majestic", "hebbal"],
["sunkadkatte", "vijayanagar", "nayandahalli", "banashankari", "silk board"],
["bommanhalli", "silk board", "banashankari", "nayandahalli", "vijayanagar", "sunkdagatte"],
["sunkadgatte", "vijayanagar", "nayandahalli", "banashankari", "silk board"],
["kammanahalli", "bayyapanahalli", "indiranagar 100ft road", "domlur layout", "inner ring road", "kormangala", "silk board", "btm layout", "banashankari", "kadirenahalli cross", "kumaraswamy layout"],
["maekhri circle", "sadhashivanagar", "malleshwaram circle", "navrang"],
["rt nagar", "kr market"],
["btm layout", "silk board", "agara", "marathahalli", "kr puram", "rama murthy nagar junction", "kalyan nagar"],
["btm layout", "silk board", "agara", "marathahalli", "kr puram", "rama murthy nagar junction", "kalyan nagar"],
["via hebbal", "kalyan nagar"],
["puttenahalli", "east end", "silk board", "marathahalli"],
["agara", "marathahalli", "kr pura rly station", "ramamurthy nagar", "iti circle"],
["silk board", "agara", "marathahalli", "vydehi hospital", "itpl"],
["arekere gate", "bilekahalli,jayadeva hospital(shoppers stop)", "silk board", "agara", "marathahalli", "vydehi hospital", "itpl"],
["gottigere", "bilekahalli,jayadeva hospital(shoppers stop)", "silk board", "agara", "marathahalli", "vydehi hospital", "hope form"],
["agara", "marathahalli", "kr pura rly station"],
["marathahalli", "kundalahalli"],
["hebbal", "kr pura", "marathahalli", "kundalahalli"],
["kr pura", "hoodi circle", "graphite signal"],
["chandra layout", "nayandahalli", "pesit", "kathriguppe", "banashankari", "silk board", "agara", "marathahalli"],
["yeshvantapur", "vijayanagar"],
["nayandahalli", "pesit", "banashankari", "sangam circle", "btm layout", "silk board", "marathahalli"],
["east end", "silk board", "marathahalli"],
["uttarahalli,banashankari,east end", "silk board", "marathahalli"],
["marathahalli", "silk board"],
["koramangla water tank", "madiwala"],
["kalyan nagar", "hebbal", "bel circle", "hmt", "jalahalli cross", "peenya 2nd stage"],
["pesit", "banashankari", "silk board", "bommanhalli", "hosa road junction"],
["pesit", "somapura toll", "kanakapura road toll", "bannerghatta road toll", "electronic city toll"]]


def flatten_list(_2d_list):
    flat_list = []
    # Iterate through the outer list
    for element in _2d_list:
        if type(element) is list:
            # If the element is of type list, iterate through the sublist
            for item in element:
                flat_list.append(item)
        else:
            flat_list.append(element)
    return flat_list

route = flatten_list(route)

route.sort()

res = []
for i in route:
    if i not in res:
        res.append(i)
for x in route:
    with open("del.txt", "a+") as f:
        f.write(f'<option value="{x}">{x}</option> \n')