from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):#remove/replace this with bus routes 
    id = db.Column(db.Integer, primary_key=True)
    # data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    bus_num = db.Column(db.String(100))
    Travel_id = db.Column(db.String(150))
    from_loc = db.Column(db.String(100))
    to = db.Column(db.String(100))
    ###setting relationship BETWEEN notes and users(foriegn keys is the concept)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))#note the smalls in "user.id"

# class reminder(db.model): and code like above, follow one to many relationship

    


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True,unique=True)
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    password = db.Column(db.String(150))
    phoneNumber = db.Column(db.String(20), unique=True)
    notes = db.relationship('Note')#note the capitals in "Note"
    




#####defs####



# #to check for case
# for x in route:
#     for y in x:
#         if y.lower() != y:
#             print(y)
            






def get_bus(from_loc,to):
    number = ["1",
    "2",
    "9",
    "12",
    "13",
    "14",
    "18",
    "20",
    "21",
    "22",
    "25",
    "26",
    "28",
    "30",
    "34",
    "38",
    "41",
    "44",
    "45",
    "59",
    "61",
    "63",
    "64",
    "75",
    "87",
    "88",
    "96",
    "104",
    "115",
    "124",
    "137",
    "138",
    "139",
    "173",
    "174",
    "176",
    "180",
    "181",
    "186",
    "188",
    "189",
    "190",
    "197",
    "201",
    "100E",
    "107D",
    "112E",
    "114E",
    "115A",
    "119A",
    "12B",
    "12D",
    "12E",
    "131,131F",
    "137A",
    "138D",
    "13B",
    "13C",
    "13E",
    "13F",
    "13S",
    "141A",
    "141E",
    "144G",
    "144H",
    "144K",
    "15A",
    "15E",
    "162A",
    "173A",
    "188B",
    "190A",
    "201D",
    "25E",
    "2A",
    "2B",
    "2F",
    "33E",
    "34A",
    "34B",
    "34C",
    "34E",
    "34S",
    "3B",
    "3C",
    "3E",
    "43B",
    "43E",
    "45A",
    "45B",
    "45C",
    "45E",
    "45F",
    "45J",
    "57A",
    "60A",
    "60E",
    "61A,G",
    "61B",
    "61C",
    "61F",
    "61J",
    "65B",
    "75B",
    "77B",
    "77C",
    "80A",
    "80B",
    "80C",
    "86E",
    "88A",
    "90E",
    "96A",
    "96B",
    "96C",
    "96D",
    "96F",
    "99E",
    "201G",
    "201J",
    "201H",
    "201M",
    "201MA",
    "201MD",
    "201MJ",
    "201R (Volvo)",
    "201RC (AC Marcopolo)",
    "201S ( Corona AC)",
    "201U",
    "201V",
    "210A",
    "210G",
    "210U",
    "210R",
    "211N",
    "211T",
    "213V",
    "215Z",
    "222A",
    "222D",
    "223J",
    "224L",
    "225",
    "226W",
    "226KG",
    "227BA",
    "227CA",
    "234B",
    "235N",
    "240P",
    "248",
    "248SA/60A",
    "270H",
    "270HA",
    "273C",
    "276G (Volvo)",
    "276N",
    "278",
    "278B",
    "279",
    "279F",
    "282A",
    "282G",
    "285",
    "285 MK",
    "285 M",
    "288",
    "288 A",
    "298 M",
    "300",
    "300 E",
    "302A, 302F",
    "300Q",
    "301E",
    "314",
    "314A",
    "314B",
    "314D",
    "314E",
    "314F",
    "314G",
    "314H",
    "314K",
    "314N",
    "315K",
    "317",
    "315-L",
    "328B",
    "328H",
    "328HA",
    "329C",
    "329G",
    "334E",
    "356M",
    "356J",
    "365M",
    "366P",
    "369M",
    "375",
    "375A (Volvo)",
    "375 B",
    "378",
    "378A",
    "378B",
    "399",
    "399C",
    "401",
    "401B",
    "401M",
    "401K",
    "401P",
    "401S",
    "402",
    "402 B & 402 D",
    "402 C",
    "402G",
    "402M",
    "410",
    "410C",
    "410D",
    "410E",
    "412",
    "414",
    "415S",
    "500A",
    "500A (Volvo)",
    "500AA",
    "500BM (Volvo)",
    "500C",
    "500C (Volvo)",
    "500CB (Volvo)",
    "500CN (Volvo)",
    "500D",
    "500DB (Volvo)",
    "500DE (Volvo)",
    "500DF(Volvo)",
    "500K(Volvo)",
    "500KB(Volvo)",
    "500KG(Volvo)",
    "500KM(Volvo)",
    "500KR(Volvo)",
    "505 (Volvo)",
    "505A (Volvo)",
    "507",
    "600K(Volvo)",
    "600NL(Volvo)"
    ]



    route = [["jayanagar 4th block", "south end", "gandhi bazaar", "goods shed road", "majestic", "malleshwaram", "yeshwanthpur railway station"],
    ["ssmrv", "jayanagar", "lalbagh", "town hall", "j.p.nagar 6th phase"],
    ["ssmrv", "jayanagar", "lalbagh", "town hall", "indira gandhi circle"],
    ["jp nagar 15th cross", "ssmrv", "tel exchange", "ilyas nagar"],
    ["lalbagh", "corporation", "majestic", "sujatha talkies", "ilyas nagar"],
    ["ramakrishna ashram", "gandhi bazaar", "jayanagar 9th block"],
    ["gandhi bazaar", "jayanagar 4th block", "east end", "btm"],
    ["gandhi bazaar", "jayanagar 4th block"],
    ["mysore road satellite bus stop", "hoskerehalli cross", "kamakya", "jp nagar 6th phase", "j.p.nagar 3rd phase"],
    ["lalbagh", "nanda theatre", "sangam circle", "banashankari"],
    ["lalbagh", "yediyur", "monotype", "yarabnagar"],
    ["lalbagh", "yediyur", "banashankari bda complex", "padmanabhanagar"],
    ["lalbagh", "yediyur", "jayanagar 7th block", "banashankari bus stand"],
    ["jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand","richmond circle", "dayanandsagar college", "shivajinagar"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand", "richmond circle", "shivajinagar"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand", "shivajinagar"],
    ["shanthi talkies", "gandhi bazaar", "chamarajpet", "kr market", "corporation", "swastik", "malleshwaram bus station"],
    ["basavanagudi", "kumarswamy layout", "padmanabhanagar"],
    ["kr market", "basavanagudi", "kumarswamy layout"],
    ["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "18th main", "jayanager 9th block"],
    ["indian express", "richmond circle", "k h road", "lalbagh", "south end circle", "jayanagar 3rd block", "jayanagar 4th block", "jayanagar 9th block"],
    ["jayanagar 4th block", "madhavan park", "ashoka pillar", "lalbagh west gate", "kims hospital/makkalakoota"],
    ["jayanagar 4th block", "madhavan park", "ashoka pillar", "lalbagh west gate", "j c road", "corporation"],
    ["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "sanjay gandhi hospital", "jayanager east end (jayadeva hospital)", "udupi garden", "btm"],
    ["corporation", "lalbagh", "ashoka pillar", "jayanagar 4th block", "sanjay gandhi hospital", "jayanager east end (jayadeva hospital)", "j.p.nagar 3rd phase"],
    ["ashoka pillar", "siddapuram"],
    ["jayanagar 4th block", "ashoka pillar", "gandhi bazaar", "k r market", "vidhan soudha", "shivananda", "vyalikaval"],
    ["gandhi bazaar", "chamarajpet", "kr market", "corporation", "kaveri bhavan", "vasanth nagar", "jc nagar", "rehmath nagar"],
    ["chamarajpet", "kr market", "town hall", "mysore bank circle", "shivananda circle", "malleshwaram circle"],
    ["srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["vivekanandanagar", "srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["srinivasanagar", "ramakrishna ashram", "lalbagh west gate", "shantinagar"],
    ["double road", "richmond circle", "brigade road", "mg road", "trinity circle", "cmh road", "indiranagar"],
    ["malleswaram 8th cross", "swastik", "corporation", "lalbagh main gate"],
    ["srinivasanagar", "ganesh bhavan", "ramakrishna ashram", "uma talkies", "kr market", "corporation"],
    ["srinivasanagar", "ganesh bhavan", "ramakrishna ashram", "uma talkies", "kr market", "corporation"],
    ["banashankari 1st stage", "hanmanthnagara ward office", "chamarajpet", "kr market", "cantonment railway station", "jc nagar", "rehmath nagar"],
    ["banashankari 1st stage", "chamarajpet", "k r market"],
    ["banashankari 1st stage", "chamarajpet", "k r market"],
    ["banashankari 1st stage", "chamarajpet", "k r market", "corporation"],
    ["banashankari 1st stage", "chamarajpet", "k r market"],
    ["watertank", "banashankari 1st stage", "chamarajpet", "k r market", "corporation"],
    ["janta bazaar", "banashankari 1st stage", "chamarajpet", "k r market", "corporation"],
    ["banashankari 1st stage", "chamarajpet", "k r market", "corporation"],
    ["mysore road"],
    ["maruti mandir (vijayanagar)", "garage (vijayanagar)", "attiguppe (vijayanagar)", "deepanjali nagar", "bapujinagar", "chamarajpet", "ram mmandir (chamarajpet)", "makkalakoota", "kr market"],
    ["jayanagar 9th block", "jayanagar south end", "gandhi bazaar", "mysore road satellite bus stop"],
    ["vijayanagar"],
    ["vijayanagar", "rajajinagar 6th block", "sujatha"],
    ["vijayanagar (maruti mandir (vijayanagar))", "vijayanagar", "rajajinagar 6th block", "sujatha"],
    ["vijayanagar"],
    ["vijayanagar", "west of chord road", "yeshwanthpur"],
    ["via south end", "gandhi bazaar", "chamarajpet", "magadi road"],
    ["rajajinagar"],
    ["malleshwaram", "srirampura", "rajajinagar"],
    ["chamarajpet", "magadi road"],
    ["saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mmandir (chamarajpet)", "sujatha talkies", "okalipuram"],
    ["nandini layout", "saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mmandir (chamarajpet)", "sujatha talkies", "okalipuram"],
    ["nandini layout", "saraswathipura", "rajajinagar 1st block", "navrang", "esi", "ram mmandir (chamarajpet)", "sujatha talkies", "okalipuram"],
    ["jayanagar 4th block", "kempegowda bus station", "magadi road"],
    ["okalipuram", "magadi road", "prasanna", "tollgate", "pipe line", "railway gate"],
    ["sujatha", "ram mmandir (chamarajpet)"],
    ["sujatha"],
    ["central", "malleshwaram", "rajajinagar", "modi hospital", "basaveshwarnagar", "sujatha"],
    ["malleshwaram 8th main"],
    ["sujatha", "basaveshwarnagar", "modi hospital", "rajajinagar", "malleshwaram", "central"],
    ["sujatha", "basaveshwarnagar"],
    ["sujatha","ram mmandir (chamarajpet)", "basaveshwarnagar"],
    ["central", "devaiah park", "modi hospital"],
    ["modi hospital"],
    ["mount carmel", "shivajinagar", "shantinagar", "adugodi", "kormangala"],
    ["sadashivanagar", "guttahalli main road", "link road", "central"],
    ["shivajinagar", "jayanagar 4th block"],
    ["indian express", "richmond cirlce", "kormangala"],
    ["cbi", "shankar mutt"],
    ["indian express", "corporation", "kr market"],
    ["rt nagar", "matadahalli", "kg road"],
    ["kg road"],
    ["cqal", "borebank road"],
    ["100ft road indiranagar", "ulsoor"],
    ["malleshwaram", "mount carmel", "indian express", "ulsoor", "indiranagar"],
    ["malleshwaram", "mount carmel", "indian express", "ulsoor", "indiranagar"],
    ["corporation", "residency road", "mg road", "ulsoor", "indiranagar", "thippasandra cross"],
    ["vidhan soudha", "shivajinagar", "ulsoor", "indiranagar", "thippasandra cross"],
    ["ulsoor", "indiranagar", "thippasandra cross"],
    ["shivajinagar"],
    ["yeshwanthpur", "mekhri circle", "shivajinagar"],
    ["shivajinagar"],
    ["jayanagar 4th block", "btm", "silk board"],
    ["kempegowda bus station", "shantinagar"],
    ["wilson garden", "majestic"],
    ["mekhri circle", "vyalikaval", "malleshwaram circle", "navrang", "vijayanagar", "maruti mandir (vijayanagar)"],
    ["mekhri circle", "yeshwanthpur"],
    ["magadi road", "kr market", "lalbagh west gate", "jayanagar 4th block"],
    ["vyalikaval", "malleshwaram circle"],
    ["hanumantanagar", "town hall", "malleshwaram"],
    ["hanumantanagar", "jc road", "town hall", "majestic", "malleshwaram"],
    ["via majestic", "malleshwaram circle"],
    ["via hanumantanagar", "ramakrishna ashram", "lalbagh", "richmond circle", "ulsoor", "indiranagar"],
    ["via indiranagar", "ulsoor", "shivajinagar", "cantonment railway station", "jc nagar", "rt nagar"],
    ["indiranagar", "ulsoor", "austin town", "vivek nagar", "kormangala 100ft road", "madivala", "silk board", "banashankari", "kathriguppe", "hoskerehalli cross", "srinivasanagar"],
    ["indiranagar 100 feet road", "domlur layout", "inner ring road", "kormangala"],
    ["thippasandra cross", "cmh road", "indiranagar 100 feet road", "domlur layout", "inner ring road", "kormangala", "madivala", "silk board", "btm", "jayanagar 5th block"],
    ["thippasandra cross", "cmh road", "indiranagar 100 feet road", "inner ring road", "kormangala", "madivala", "silk board", "banashankari", "devegowda petrol bunk"],
    ["madivala", "silk board", "btm", "jayanagar 5th block", "banashankari", "devegowda petrol bunk"],
    ["thippasandra cross", "cmh road", "indiranagar 100 feet road", "inner ring road", "kormangala", "madivala", "silk board", "banashankari", "devegowda petrol bunk", "pesit", "nayandahalli cross", "attiguppe (vijayanagar)"],
    ["thippasandra cross", "cmh road", "indiranagar 100 feet road", "domlur layout", "inner ring road", "kormangala"],
    ["btm", "silk board", "dell"],
    ["btm", "silk board", "indiranagar"],
    ["beml gate", "thippasandra cross", "cmh road", "indiranagar 100 feet road", "kormangala", "madivala", "silk board", "banashankari", "kathriguppe", "hoskerehalli cross", "bank colony", "hanumantanagar"],
    ["beml gate", "thippasandra cross", "cmh road", "indiranagar 100 feet road", "inner ring road", "kormangala", "madivala", "silk board", "btm", "jayanagar 5th block", "banashankari", "kadirenahalli cross"],
    ["indiranagar 100 feet road", "cmh road", "trinity circle", "adugodi", "madivala", "silk board", "btm", "jayanagar 5th block"],
    ["devegowda petrol bunk", "banashankari", "btm", "silk board", "madivala", "kormangala", "inner ring road", "indiranagar 100 feet road"],
    ["east end", "btm", "silk board", "kormangala water tank", "kormangala sony world"],
    ["kr market", "basavanagudi","dayanandsagar college","kumarswamy layout"],
    ["banashankari", "jayanagar 4th block", "shantinagar bus stand","dayanandsagar college","kumarswamy layout"],
    ["kr market", "basavanagudi","dayanandsagar college"],
    ["kr market", "basavanagudi","dayanandsagar college","kumarswamy layout"],
    ["banashankari", "konanakunte cross", "kaggalipura"],
    ["banashankari", "konanakunte cross", "art of living", "udayapura", "sln stores(appaji stores)"],
    ["banashankari", "konanakunte cross", "kaggalipura", "kebbagodi cross"],
    ["banashankari", "konanakunte cross", "gottigere"],
    ["mctc", "nayandanahalli", "kengeri"],
    ["via basavanagudi", "banashankari", "uttarahalli"],
    ["nayandahalli", "banashankari"],
    ["via banashankari", "uttarahalli"],
    ["via ideal homes rajarajeshwarinagar gate", "rajarajeswari temple"],
    ["banashankari", "btm", "silk board"],
    ["via viajayanagar", "mctc", "chamarajpet"],
    ["kamakshipalya", "khb colony", "vijayanagar", "mctc", "chamarajpet"],
    ["hegganahalli", "sunkadakatte", "kamakshipalya", "khb colony", "vijayanagar", "mctc"],
    ["via sunkadakatte"],
    ["mathikere", "mekhri circle", "shivajinagar", "shantinagar", "jayanagar 4th block"],
    ["via jayanagar ttmc", "lalbagh", "corporation", "swastik", "malleshwaram 18th cross"],
    ["kempegowda bus station", "corporation", "shantinagar", "madivala", "bommanahalli"],
    ["bel circle", "mathikere", "kempegowda bus station", "kr market", "basavanagudi"],
    ["mekhri circle", "shivajinagar", "ulsoor"],
    ["corporation", "kr market"],
    ["majestic", "shivananda", "mekhri circle", "hebbal", "kodighalli", "yelahanka police station", "hunsamanhalli", "kodagulati", "hosahalli"],
    ["majestic", "shivananda", "mekhri circle", "hebbal", "kodighalli", "yelahanka police station", "hunsamanhalli", "kodagulati"],
    ["majestic", "shivananda", "mekhri circle", "hebbal", "kodighalli", "yelahanka nes", "ananthapura gate"],
    ["majestic", "shivananda", "mekhri circle", "hebbal", "kodighalli", "yelahanka nes", "ananthapura gate", "rajankunte"],
    ["mekhri circle", "hebbal", "kodighalli", "yelahanka nes", "ananthapura gate","rajankunte"],
    ["mekhri circle", "hebbal", "kodighalli"],
    ["mekhri circle", "hebbal", "sahakar nagar"],
    ["shivananda", "mekhri circle", "hebbal", "kodighalli", "yelahanka police station", "yelahanka old town"],
    ["frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "shivajinagar"],
    ["iti circle", "ramamurthy nagar", "ring road", "banaswadi", "uttam sagar", "ayyappa temple", "indian oil", "maruthi sevanagar", "jai bharath nagar", "itc", "mosque road", " frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "shivajinagar"],
    ["babusapalya", "mantap", "om shakti temple", "uttam sagar", "ayyappa temple", "indian oil", "maruthi sevanagar", "jai bharath nagar", "itc", "mosque road", "frazer town", "coles park", "bamboo bazaar", "queens road", "indian express", "vidhan soudha", "kr circle", "mysore bank", "kbs"],
    ["shivajinagar", "shantinagar", "jayanagar 4th block"],
    ["banaswadi", "shivajinagar", "shantinagar"],
    ["mg road", "ulsoor", "indiranagar", "thippasandra", "beml gate"],
    ["mg road", "ulsoor", "indiranagar", "thippasandra", "beml gate", "cv raman nagar", "kaggadasapura"],
    ["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate"],
    ["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "mallesh palya"],
    ["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "cv raman nagar", "kaggadasapura"],
    ["town hall", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "vignana nagar"],
    ["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "gm palya"],
    ["corporation", "mayo hall", "ulsoor", "indiranagar", "thippasandra", "beml gate", "gm palya"],
    ["thippasandra", "cmh road", "trinity circle", "vellara junction", "kh road", "lalbagh west gate", "national college", "hanumantanagar"],
    ["mg road", "ulsoor", "indiranagar", "thippasandra", "mallesh palya"],
    ["kasturinagar", "channasandra railway bridge", "ramamurthy nagar"],
    ["corporation", "bishop cottons", "m g road", "ulsoor", "indiranagar depot", "byapanahalli", "tin factory", "k r puram", "hoskote"],
    ["isolation hospital", "kasturinagar"],
    ["kadugodi", "varthur", "bommasandra"],
    ["kadugodi", "whitefield", "varthur", "bommasandra", "sarjapur", "indiabele"],
    ["town hall", "corporation", "mg road", "domlur layout", "hal", "marathahalli", "siddapuram", "kodi", "varthur", "madhura nagar", "vaalepura"],
    ["mg road", "domlur layout", "hal", "marathahalli", "siddapuram", "kodi", "varthur", "madhura nagar", "vaalepura"],
    ["hal", "marathahalli", "vathoor kodi", "whitefield", "kadugodi", "(kbs to itpl)", "domlur layout", "hal", "marathahalli", "kundalahalli gate"],
    ["chandapura", "electronic city", "madivala", "silk board"],
    ["mekhri circle", "kempegowda bus station", "madivala"],
    ["kempegowda bus station", "dairy circle"],
    ["jalahalli cross", "kr market", "lalbagh", "jayanagar 4th block"],
    ["jayanagar east end", "jayanagar 4th block", "gandhi bazaar", "mctc"],
    ["via kengeri", "uttarahalli","jayanagar ttmc"],
    ["kengeri", "uttarahalli", "banashankari", "silk board", "bommanahalli"],
    ["jayanagar", "banashankari", "uttarahalli", "kengeri"],
    ["via uttarahalli", "konanakunte cross", "gottigere", "bettadasapura", "neeladri", "wipro"],
    ["jayanagar 5th block", "jp nagar 1st phase", "jambusavari dinne", "gottigere", "378 route"],
    ["attibelle", "sarjapur", "dommsandra", "varthur", "kadugodi"],
    ["attibelle", "sarjapur"],
    ["vidyaranyapura", "mathikere", "hoskerehalli cross"],
    ["vidyaranyapura", "mathikere", "yeshwanthpur", "isckon", "west of chord road", "vijayanagar"],
    ["gorguntepalya", "kamakshipalya", "nagarbhavi bda complex", "kengeri satellite town"],
    ["kengeri satellite town", "west of chord road", "yeshwanthpur"],
    ["west of chord road"],
    ["rajajinagar", "vijayanagar", "nayandahalli", "kamakya"],
    ["majestic", "mekhri circle", "hebbal", "yelahanka nes", "upanagara"],
    ["mekhri circle", "hebbal", "yelahanka nes", "upanagara"],
    ["mekhri circle", "hebbal", "yelahanka nes", "upanagara"],
    ["kr road", "kr market", "kempegowda bus station", "hebbal"],
    ["banashankari", "kr road", "kr market", "majestic", "hebbal"],
    ["sunkadakatte", "vijayanagar", "nayandahalli", "banashankari", "silk board"],
    ["bommanahalli", "silk board", "banashankari", "nayandahalli", "vijayanagar", "sunkdagatte"],
    ["sunkadakatte", "vijayanagar", "nayandahalli", "banashankari", "silk board"],
    ["kammanahalli", "bayyapanahalli", "indiranagar 100 feet road", "domlur layout", "inner ring road", "kormangala", "silk board", "btm", "banashankari", "kadirenahalli cross", "kumarswamy layout"],
    ["maekhri circle", "sadashivanagar", "malleshwaram circle", "navrang"],
    ["rt nagar", "kr market"],
    ["btm", "silk board", "agara", "marathahalli", "k r puram", "rama murthy nagar junction", "kalyan nagar"],
    ["btm", "silk board", "agara", "marathahalli", "k r puram", "rama murthy nagar junction", "kalyan nagar"],
    ["via hebbal", "kalyan nagar"],
    ["puttenahalli", "east end", "silk board", "marathahalli"],
    ["agara", "marathahalli", "k r puram rly station", "ramamurthy nagar", "iti circle"],
    ["silk board", "agara", "marathahalli", "vydehi hospital", "itpl"],
    ["arekere gate", "bilekahalli","jayadeva hospital(shoppers stop)", "silk board", "agara", "marathahalli", "vydehi hospital", "itpl"],
    ["gottigere", "bilekahalli","jayadeva hospital(shoppers stop)", "silk board", "agara", "marathahalli", "vydehi hospital", "hope form"],
    ["agara", "marathahalli", "k r puram rly station"],
    ["marathahalli", "kundalahalli"],
    ["hebbal", "k r puram", "marathahalli", "kundalahalli"],
    ["k r puram", "hoodi circle", "graphite signal"],
    ["chandra layout", "nayandahalli", "pesit", "kathriguppe", "banashankari", "silk board", "agara", "marathahalli"],
    ["yeshwanthpur", "vijayanagar"],
    ["nayandahalli", "pesit", "banashankari", "sangam circle", "btm", "silk board", "marathahalli"],
    ["east end", "silk board", "marathahalli"],
    ["uttarahalli","banashankari","east end", "silk board", "marathahalli"],
    ["marathahalli", "silk board"],
    ["kormangala water tank", "madivala"],
    ["kalyan nagar", "hebbal", "bel circle", "hmt", "jalahalli cross", "peenya 2nd stage"],
    ["pesit", "banashankari", "silk board", "bommanahalli", "hosa road junction"],
    ["pesit", "somapura toll", "kanakapura road toll", "bannerghatta road toll", "electronic city toll"]]
    dict1 = dict(zip(number,route))
    #print(dict1)
    #print(from_loc,to)
    final_route = []
    final_number=[]

    for x in dict1:
        # print(dict1[x])
        if from_loc in dict1[x]:
            if to in dict1[x]:
                # print("yes")
        
                final_route.append(dict1[x])
                final_number.append(x)
    return dict(zip(final_number,final_route))





import requests
from bs4 import BeautifulSoup
from requests.sessions import dispatch_hook

def get_distance(a,b):
    # URL 
    url = f"https://www.google.com/search?&q=distace+between+{a}+bus+stop+and+{b}+bus+stop+bengaluru" 
    url = url.replace(" ", "+")
    #print(url)
    #Sending HTTP request
    req = requests.get(url)
    
    # Pulling HTTP data from internet
    sor = BeautifulSoup(req.text, "html.parser") 
    
    # Finding temperature in Celsius
    temp = sor.find("div", class_='BNeawe').text
    temp = temp.replace(")", "")  
    temp = temp.replace("(", "")  
    temp = temp.split()

    # print(temp)
    lol = temp.index("km")
    y = lol-1
    distance = temp[y]
    return distance

# lmao = get_distance("shantinagar bus stand","shivajinagar")
# print(lmao)


